--[[

---//==================================================\\---
--|| > About Library                                    ||--
---\\==================================================//---

    Library:    GodLib
    Version:    0.01
    Author:     Devn

--]]

---//==================================================\\---
--|| > Initialization                                   ||--
---\\==================================================//---

assert(load(Base64Decode("G0x1YVIAAQQEBAgAGZMNChoKAAAAAAAAAAAAAQI2AAAABkBAAAeAQAAbQAAAFwAAgAHAAAAIAACABkBAAAdAQQAbQAAAFwAAgAGAAQAIAACCBkBAAAcAQgAbQAAAFwAAgAFAAgAIAICDBkBAAAfAQgAbQAAAFwAAgAMAAAAIAACFBgBDAGUAAAAKQICGBoBDAEHAAwAdQAABBsBDAGVAAAAKQACIBsBDAGWAAAAKQICIBsBDAGXAAAAKQACJBsBDAB2AgAAIAICHJQABAAgAgIkLwAAACoDFigoAxosKgMaMCAAAiiVAAQAIAICNJYABAAgAAI4fAIAAHQAAAAQLAAAAU2NyaXB0TmFtZQAEAwAAAF9HAAQSAAAAR29kTGliX1NjcmlwdE5hbWUABAoAAABHb2RTY3JpcHQABA4AAABTY3JpcHRWZXJzaW9uAAQVAAAAR29kTGliX1NjcmlwdFZlcnNpb24ABAUAAAAwLjAxAAQLAAAAU2NyaXB0RGF0ZQAEEgAAAEdvZExpYl9TY3JpcHREYXRlAAQNAAAATm90IFJlbGVhc2VkAAQNAAAAQ2xvc2VkQWNjZXNzAAQUAAAAR29kTGliX0Nsb3NlZEFjY2VzcwAEBwAAAHN0cmluZwAECAAAAGdmb3JtYXQABAYAAABjbGFzcwAECgAAAENhbGxiYWNrcwAEBwAAAF9faW5pdAAEBQAAAEJpbmQABAUAAABDYWxsAAQHAAAAT25Mb2FkAAQMAAAATWVzc2FnZVR5cGUABAUAAABJbmZvAAQHAAAAYmVmNzgxAAQIAAAAV2FybmluZwAEBwAAADgxYmVmNwAEBgAAAEVycm9yAAQHAAAAZjc4MTgzAAQLAAAAUHJpbnRMb2NhbAAEBwAAAEZvcm1hdAAHAAAAJgAAADAAAAABAQsWAAAASwAAAKYAAABkQAAAgQAAANUAgAABAQAAocACgIxBQAABggAARsJAAIACgAJdggABgQIBABaCAgRGwkAAh0KBAF0CAAGdgQAAAAAAA6CA/H8fAAABHwCAAAUAAAADAAAAAAAA8D8EBQAAAGdzdWIABAIAAAB7AAQJAAAAdG9zdHJpbmcABAIAAAB9AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAADwAAAABAAIDAAAASwAAAApAAIAfAIAAAQAAAAQMAAAAX19DYWxsYmFja3MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAEYAAAADAAYOAAAAxwBAAMdAgAHbQAAAF4AAgMcAQAALAQAAygCBAMZAQADHgMABBwFAAAdBAAJAAQAB3UCAAR8AgAADAAAABAwAAABfX0NhbGxiYWNrcwAEBgAAAHRhYmxlAAQHAAAAaW5zZXJ0AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAFAAAAACAQsUAAAAhwBAAIdAAAGbAAAAF4ADgIZAQADHAEAAx0CAAZ0AAQEXwAGAwAEAAwaCQAAHwkAESwIAAKYCAABkQgAAHQIAAd1BAACigAAAI0H9fx8AgAAEAAAABAwAAABfX0NhbGxiYWNrcwAEBwAAAGlwYWlycwAEBgAAAHRhYmxlAAQHAAAAdW5wYWNrAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAFwAAAAAAAMFAAAABgBAAAxAQACBgAAAHUCAAR8AgAADAAAABAoAAABDYWxsYmFja3MABAUAAABDYWxsAAQFAAAATG9hZAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAABxAAAAAgAJDQAAAJxAgAAXQACAhgBAAIdAQAHGgEAABsFAAEEBAQCGQUEAwAEAAQACAAAdAYAC3UAAAB8AgAAGAAAABAwAAABNZXNzYWdlVHlwZQAEBQAAAEluZm8ABAoAAABQcmludENoYXQABAcAAABGb3JtYXQABEAAAAA8Zm9udCBjb2xvcj0iI2Y3ODFiZSI+ezF9OjwvZm9udD4gPGZvbnQgY29sb3I9IiN7Mn0iPnszfTwvZm9udD4ABAsAAABTY3JpcHROYW1lAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAcwAAAHcAAAABAQQFAAAATABAAOYAAABeAAAAXwAAAB8AgAABAAAABAgAAABnZm9ybWF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAA="), nil, "bt", _ENV))()
